# Model
model:
  rest_name: namespacetype
  resource_name: namespacetypes
  entity_name: NamespaceType
  package: squall
  group: core/namespace
  description: Returns the type of the specified namespace.

# Attributes
attributes:
  v1:
  - name: type
    description: the namespace type for the current namespace.
    type: string
    exposed: true
    read_only: true
    autogenerated: true
